name: Sonarr
version: 0.4.2
slug: sonarr
description: '[老王杂谈说]：智能PVR适用于新闻组和BitTorrent用户'
url: https://ghfast.top/github.com/hassio-addons/addon-sonarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8989]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8989/tcp: 8989
image: ghcr.nju.edu.cn/hassio-addons/sonarr/{arch}
