name: Roundcube
version: 1.1.1
slug: roundcube
description: Roundcube webmail client
url: https://ghfast.top/github.com/erik73/hassio-addons
arch:
- aarch64
- amd64
- armv7
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:email
map:
- ssl
services:
- mysql:need
ports:
  80/tcp: null
ports_description:
  80/tcp: Roundcube
hassio_api: true
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  certfile: str
  keyfile: str
  ssl: bool
image: ghcr.mirrors.cqupt.edu.cn/erik73/roundcube/{arch}
