---
build_from:
  aarch64: ghcr.mirrors.cqupt.edu.cn/gramps-project/grampsweb:latest
  amd64: ghcr.mirrors.cqupt.edu.cn/gramps-project/grampsweb:latest
codenotary:
  signer: alexandrep.github@gmail.com
