{
  "name": "Virtual DSM",
  "version": "1.0.0",
  "slug": "virtual_dsm",
  "description": "Run Virtual DSM in Home Assistant",
  "url": "https://github.com/yourusername/hassio-addons/tree/main/virtual-dsm",
  "arch": [
    "amd64"
  ],
  "startup": "application",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 5000,
  "panel_icon": "mdi:nas",
  "ports": {
    "5000/tcp": 5000,
    "5001/tcp": 5001
  },
  "ports_description": {
    "5000/tcp": "DSM Web Interface",
    "5001/tcp": "DSM Secure Interface"
  },
  "host_network": true,
  "devices": [
    "/dev/kvm"
  ],
  "privileged": [
    "NET_ADMIN",
    "SYS_ADMIN"
  ],
  "options": {
    "memory": 2048,
    "cpu_cores": 2,
    "disk_size": "8G",
    "dsm_version": "7.2",
    "serial_number": "",
    "mac_address": ""
  },
  "schema": {
    "memory": "int(1024,16384)",
    "cpu_cores": "int(1,8)",
    "disk_size": "str",
    "dsm_version": "list(7.0|7.1|7.2)",
    "serial_number": "str?",
    "mac_address": "str?"
  },
  "init": false
}