---
build_from:
  aarch64: ghcr.mirrors.cqupt.edu.cn/home-assistant/aarch64-base:3.20
  amd64: ghcr.mirrors.cqupt.edu.cn/home-assistant/amd64-base:3.20
  armhf: ghcr.mirrors.cqupt.edu.cn/home-assistant/armhf-base:3.20
  armv7: ghcr.mirrors.cqupt.edu.cn/home-assistant/armv7-base:3.20
  i386: ghcr.mirrors.cqupt.edu.cn/home-assistant/i386-base:3.20
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  DEHYDRATED_VERSION: 0.8.0
