---
#  https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.nju.edu.cn/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.nju.edu.cn/home-assistant/amd64-base:3.22"
  armv7: "ghcr.nju.edu.cn/home-assistant/armv7-base:3.22"
  #  armhf: "ghcr.nju.edu.cn/home-assistant/armhf-base:3.22"

codenotary:
  #  signer: ha.cas.secret@gmail.com
  base_image: notary@home-assistant.io
