name: n8n
version: "1.111.1"
upstream: 1.62.4
slug: n8n
description: >-
  [老王杂谈说]：
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  5678/tcp: 5678
ports_description:
  5678/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /home/node/
environment:
  PUID: "1"
  PGID: "1"
  N8N_SECURE_COOKIE: "false"
  TINI_SUBREAPER: "true"
  N8N_USER_FOLDER: "/home/node/"
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:5678]"
ingress: false
ingress_port: 5678
options:
  USE_ENV_FILE: false
  N8N_ENV_FILES: "/home/node/config.env"
schema:
  USE_ENV_FILE: "bool"
  N8N_ENV_FILES: "str"
