build_from:
  armhf: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:18.0.1"
  armv7: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:18.0.1"
  amd64: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:18.0.1"
  i386: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:18.0.1"
