{
  "name": "YesPlayMusic",
  "version": "0.48-2",
  "slug": "yesplaymusic",
  "description": "A web-based music player for Home Assistant.",
  "arch": [
    "amd64",
    "armhf",
    "armv7", 
    "aarch64"
  ],
  "startup": "services",
  "boot": "auto",
  "ports": {
    "3000/tcp": 7080,
    "80/tcp": 7081
  },
  "webui": "http://[HOST]:[PORT:7081]",
  "ingress": true,
  "ingress_port": 80,
  "panel_icon": "mdi:music",
  "options": {},
  "schema": {}
}
