name: Otter Wiki
version: "2.14.1"
upstream: 2.7.0
slug: otterwiki
description: >-
  [老王杂谈说]：Otter Wiki是一款基于Python的协作内容管理软件，被称为维基。内容存储在git仓库中，该仓库跟踪所有更改。Markdown用作标记语言。Otter Wiki使用Python编写，采用微框架Flask。halfmoon用作CSS框架，CodeMirror用作编辑器。Font Awesome Free提供图标。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  80/tcp: 8084
ports_description:
  80/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /app-data
image: redimp/otterwiki
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
ingress: false
ingress_port: 80
