---
version: v0
slug: LocalSTTCN
name: LocalSTTCN
description: offline Speech-to-text service for Home Assistant
url: https://github.com/home-assistant/addons/blob/master/LocalSTTCN
arch:
  - amd64
init: false
discovery:
  - localstt
ingress: true
ports:
  "10300/tcp": 10300
