labels:
  maintainer: "Desmond Dong"
  io.hass.addon.changelog: |
    ## v1.0.0
    - 新版本的萤石云信令服务器
    - 提升性能和稳定性
    - 添加了配置选项
  io.hass.addon.version: "v1.0.0"
  io.hass.addon.name: "EZVIZ Cloud Signaling Receiver"
  io.hass.addon.description: "这是萤石云信令接收服务器，负责处理来自萤石云的信令消息。"
  io.hass.addon.url: "https://mp.weixin.qq.com/s/Sh1tGf7kYvgI4OiDGVQgHg"
  io.hass.addon.arch: "amd64, armhf, aarch64, armv7, i386"
  io.hass.addon.init: "false"
  io.hass.addon.startup: "services"
  io.hass.addon.ingress: "true"
  io.hass.addon.ingress_port: "7777"
  io.hass.addon.panel_icon: "mdi:camera"
  io.hass.addon.ports: |
    7777/tcp: 7777
  io.hass.addon.ports_description: |
    7777/tcp: "EZVIZ Cloud Signaling Receiver"
  io.hass.addon.hassio_api: "true"
  io.hass.addon.hassio_role: "manager"

  io.hass.addon.webui: "http://[HOST]:[PORT:7777]"
  io.hass.addon.watchdog: "http://[HOST]:[PORT:7777]"