version: '3'
services:
  EZVIZ:
    container_name: EZVIZ-server
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 7777
    ports:
      - 7777:7777/tcp
    restart: always
