version: '3'
services:
  EZVIZ:
    container_name: EZVIZ-server
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 7777
    ports:
      - 7777:7777/tcp
    restart: always

    environment:
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}