{
  "version": "1.0",
  "name": "节点小宝",
  "slug": "jdxb",
  "description": "A Home Assistant add-on for jdxb service.这是一个节点小宝客户端",
  "arch": ["amd64", "i386"],
  "startup": "services",
  "hassio_api": true,
  "hassio_role": "manager",
  "boot": "auto",
  "restart": "always",
  "host_network": true
}
