{
  "url": "https://openwrt.org/",
  "panel_icon": "mdi:router-wireless",
  "panel_admin": true,
  "apparmor": false,
  "ingress": false,
  "hassio_api": true,
  "webui": "http://[HOST]:[PORT:80]",
  "host_network": true,
  "devices": [
    "/dev/dri",
    "/dev/dri/card0",
    "/dev/dri/card1",
    "/dev/dri/renderD128",
    "/dev/vchiq",
    "/dev/video10",
    "/dev/video11",
    "/dev/video12",
    "/dev/video13",
    "/dev/video14",
    "/dev/video15",
    "/dev/video16",
    "/dev/ttyUSB0"
  ],
  "host_dbus": true,
#  "privileged": true,
  "map": [
    "config:rw",
    "share:rw",
    "media:rw",
    "ssl"
  ],
  "environment": {
    "TZ": "Asia/Shanghai",
    "DATA_DIR": "/data"
  }
}