{
  "name": "py-kms",
  "version": "73bce0b-spad3",
  "slug": "py-kms",
  "description": "这是py-kms，一个用来激活Windows和Office的服务器",
  "url": "https://github.com/djhui/hassio-addons",
  "arch": ["aarch64", "amd64"],
  "startup": "application",
  "image": "ghcr.io/thespad/py-kms",
  "boot": "auto",
  "hassio_api": true,
  "hassio_role": "manager",
  "init": false,
  "webui": "http://[HOST]:[PORT:1688]",
  "ports": {
    "1688/tcp": 1688
  },
  "ports_description": {
    "1688/tcp": "KMS Server port"
  }
}