build_from:
  armhf: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:17.2.5"
  armv7: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:17.2.5"
  aarch64: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:17.2.5"
  amd64: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:17.2.5"
  i386: "ghcr.mirrors.cqupt.edu.cn/hassio-addons/base:17.2.5"
