name: Music Assistant Server (beta)
version: 2.7.0b3
slug: music_assistant_beta
description: '[老王杂谈说]：音乐助手BETA版本。如果你想要跟上最新最好的并且不介意一些测试，请安装此版本。在Discord上关注我们以报告和讨论反馈！'
url: https://music-assistant.io
arch:
  - amd64
  - aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8094
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
  - media:rw
init: false
advanced: false
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
stage: stable
image: ghcr.nju.edu.cn/music-assistant/server
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
