{
  "name": "AList",
  "description": "A file list program that supports multiple storage.",
  "version": "1.0.0",
  "slug": "alist",
  "init": false,
  "arch": [
    "aarch64",
    "amd64",
    "armhf",
    "armv7",
    "i386"
  ],
  "ports": {
    "5244/tcp": 5244
  },
  "ports_description": {
    "5244/tcp": "Web interface"
  },
  "webui": "http://[HOST]:[PORT:5244]",
  "options": {
    "ssl": false,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "schema": {
    "ssl": "bool",
    "certfile": "str",
    "keyfile": "str"
  }
}