version: '3'
services:
  alist:
    image: xhofe/alist-aria2:latest
    container_name: alist
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /config/addons_config/alist:/opt/alist/data
    expose:
      - 5244
    ports:
      - 5244:5244/tcp
    restart: unless-stopped
    environment:
            - PUID=0
            - PGID=0
            - UMASK=022
