name: "VoceChat Server"
version: "v0.3.57"
slug: "vocechat-server"
description: "VoceChat Server Add-on for Home Assistant with persistent data"
url: "https://voce.chat/"
arch:
  - amd64
init: false
startup: services
ingress: true
ingress_port: 3000
panel_icon: mdi:chat
map:
#  - addon_config:rw
  - config:rw
#  - share:/data
  - /config/addons_config/vocechat-server:/home/vocechat-server
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "VoceChat Server"
hassio_api: true
hassio_role: manager
options:
  data_path: "/config/addons_config/vocechat-server/data"
schema:
  data_path: str
#image: "docker.io/privoce/vocechat-server"
webui: "http://[HOST]:[PORT:3000]"
watchdog: "http://[HOST]:[PORT:3000]"
#environment:
#  VOCECHAT_FCM_PROJECT_ID: ""
#  VOCECHAT_FCM_PRIVATE_KEY: ""
#  VOCECHAT_FCM_CLIENT_EMAIL: ""
#  VOCECHAT_FCM_TOKEN_URI: "https://oauth2.googleapis.com/token"
