name: "VoceChat Server"
description: "VoceChat Server Add-on for Home Assistant"

version: "v0.3.54"
slug: "vocechat-server"
arch:
  - amd64
url: https://voce.chat/
image: docker.io/privoce/vocechat-server
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "VoceChat Server"
