name: "VoceChat Server"
description: "VoceChat Server Add-on for Home Assistant"

version: "v0.3.54"
slug: "vocechat-server"
arch:
  - amd64
url: https://voce.chat/
image: docker.io/privoce/vocechat-server
map: 
  - homeassistant_config:rw
  - addon_config:rw
  - ssl:rw
  - all_addon_configs:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw
  
init: false
ingress: true
ingress_port: 3000
options: 
    WORKDIR: "/config/addons_config/Vocechat"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "VoceChat Server"
watchdog: tcp://[HOST]:[PORT:3000]
startup: services
