{
  "name": "VoceChat Server",
  "description": "VoceChat Server Add-on for Home Assistant",
  "version": "v0.3.54",
  "slug": "vocechat-server",
  "init": false,
  "arch": [
    "amd64"
  ],
  "url": "https://voce.chat/",
  "image": "docker.io/privoce/vocechat-server",

  "hassio_api": true,
  "hassio_role": "manager",
  "startup": "services",
  "ingress": true,
  "map": [
    "addon_configs:rw",
    "config:rw"
  ],
  "ingress_port": 3000,
  "options": {
    "data_dir": "/config/addons_config/vocechat"
  },
  "ports": {
    "3000/tcp": 3000
  },
  "ports_description": {
    "3000/tcp": "VoceChat Server"
  },
  "watchdog": "http://[HOST]:[PORT:3000]",
  "webui": "http://[HOST]:[PORT:3000]"
}
