name: "VoceChat Server"
description: "VoceChat Server Add-on for Home Assistant"

version: "v0.3.54"
slug: "vocechat-server"
arch:
  - armv7
  - amd64
url: https://voce.chat/

map:
  - config:rw
image: docker.io/privoce/vocechat-server:v0.3.54
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
ports:
  3009/tcp: 3000
ports_description:
  3009/tcp: "VoceChat Server"
