version: '3'
services:
  vocechat:
    image: vocechat-server:latest
    container_name: vocechat-server
    build:
      context: .
      dockerfile: Dockerfile
    command:
        "/docker-entrypoint.sh"
        - "--network.bind"
        - "0.0.0.0:3000"
        - "--network.domain"
        - "localhost"
#    environment:
#      - UID=1000
#      - GID=1000
#      - ADMIN_USER=admin
#      - ADMIN_PASSWORD=123456
#      - DOMAIN=localhost
    volumes:
      - /config/addon_config/vocechat-server:/home/vocechat-server
      - /config/addon_config/vocechat-server/data:/home/vocechat-server/data
      - /config/addon_config/vocechat-server/config:/home/vocechat-server/config

    expose:
      - 3000
    ports:
      - 3000:3000/tcp
    restart: always