labels:
  maintainer: "Desmond Dong"
  io.hass.addon.changelog: |
    ## v0.1.1
    - Updated WeChat Server addon for Home Assistant
    - Improved configuration options and documentation
  io.hass.addon.version: "v0.1.1"
  io.hass.addon.name: "WeChat Server"
  io.hass.addon.description: "不要安装,这是测试用的,关注微信号：<老王杂谈说> 获取更多内容吧"
  io.hass.addon.url: "https://github.com/djhui/hassio-addons"
  io.hass.addon.arch: "amd64, armhf, aarch64, armv7, i386"
  io.hass.addon.init: "false"
  io.hass.addon.startup: "application"
  io.hass.addon.ingress: "true"
  io.hass.addon.ingress_port: "8888"
  io.hass.addon.panel_icon: "mdi:wechat"
  io.hass.addon.map: |
    - /config/addons_config/wechat-server:/config/addons_config/wechat-server
  io.hass.addon.ports: |
    8888/tcp: 8888
  io.hass.addon.ports_description: |
    8888/tcp: "WeChat Server"
  io.hass.addon.hassio_api: "true"
  io.hass.addon.hassio_role: "manager"
  io.hass.addon.options: |
    data_path: "/config/addons_config/wechat-server/"
  io.hass.addon.schema: |
    data_path: str
  io.hass.addon.image: "docker.io/privoce/wechat-server"
  io.hass.addon.webui: "http://[HOST]:[PORT:8888]"
  io.hass.addon.watchdog: "http://[HOST]:[PORT:8888]"