{
  "name": "WeChat Server",
  "version": "v0.5.0",
  "slug": "wechat-server",
  "description": "这是一个公众号后台，连接智能助理帮你回话。关注微信号：<老王杂谈说> 获取更多内容吧",
  "url": "https://github.com/djhui/hassio-addons",
  "arch": [
    "amd64",
    "armhf",
    "armv7",
    "aarch64",
    "i386"
  ],
  "init": false,
  "startup": "services",
  "ingress": true,
  "ingress_port": 8888,
  "panel_icon": "mdi:wechat",
  "map": [
    "config:rw"
  ],
  "ports": {
    "8888/tcp": 8888
  },
  "ports_description": {
    "8888/tcp": "WeChat Server"
  },
  "hassio_api": true,
  "hassio_role": "manager",
  "options": {
    "TOKEN": "your_wechat_token",
    "HOST": "0.0.0.0",
    "APP_ID": "your_app_id",
    "ENCODING_AES_KEY": "your_encoding_aes_key",
    "ZhipuAI": "your_zhipuai_api_key",
    "data_path": "/config/addons_config/wechat-server/"
  },
  "schema": {
    "TOKEN": "str",
    "HOST": "str",
    "APP_ID": "str",
    "ENCODING_AES_KEY": "str",
    "ZhipuAI": "str",
    "data_path": "str"
  },
  "webui": "http://[HOST]:[PORT:8888]",
  "watchdog": "http://[HOST]:[PORT:8888]"
}
