version: '3'
services:
  wechat:
    image: wechat-server:latest
    container_name: wechat-server
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - /share/data/docker/wechat-server/data:/home/wechat-server/data
      - /mnt/data/supervisor/addon_configs/:/addon_configs
    expose:
      - 8888
    ports:
      - 8888:8888/tcp
    restart: always