{
  "name": "集客AC控制器",
  "version": "2.2",
  "slug": "gecoos",
  "description": "一个集客AC控制器的 Home Assistant 加载项，测试中",
  "url": "https://github.com/djhui/hassio-addons",
  "arch": ["aarch64", "amd64", "armv7", "armhf", "i386"],
  "startup": "services",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 8080,
  "webui": "http://[HOST]:[PORT:8080]",
  "ports": {
    "60650/tcp": 60650
  },
  "options": {
    "web_port": 8080,
    "api_port": 60650,
    "showtip": 1,
    "debug": 0
  },
  "schema": {
    "web_port": "int",
    "api_port": "int",
    "showtip": "int",
    "debug": "int"
  },
  "hassio_role": "manager",
  "environment": {
    "GIN_MODE": "release"
  }
}
