{
  "name": "集客AC控制器",
  "version": "2.2",
  "slug": "gecoos",
  "description": "一个集客AC控制器的 Home Assistant 加载项",
  "url": "https://github.com/djhui/hassio-addons",
  "arch": ["aarch64", "amd64", "armv7", "armhf", "i386"],
  "startup": "services",
  "boot": "auto",
  "webui": "http://[HOST]:[PORT:8080]",
  "ports": {
    "60650/tcp": 60650,
    "8080/tcp": 8080
  },
  "options": {
    "showtip": 1,
    "debug": 0,
    "web_port": 8080,
    "api_port": 60650
  },
  "ports_description": {
    "8080/tcp": "Web interface",
    "60650/tcp": "API interface"
  },
  "schema": {
    "api_port": "int",
    "showtip": "int",
    "debug": "int"
  },
  "hassio_role": "manager",
  "environment": {
    "GIN_MODE": "release"
  }
}
