build_from:
  aarch64: "ghcr.mirrors.cqupt.edu.cn/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.mirrors.cqupt.edu.cn/home-assistant/amd64-base:3.22"
  armv7: "ghcr.mirrors.cqupt.edu.cn/home-assistant/armv7-base:3.22"
  i386: "ghcr.mirrors.cqupt.edu.cn/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "Firefox Home Assistant Add-on (Edge)"
  org.opencontainers.image.description: "Docker container for Firefox. Update to the latest Firefox version on container start."
  org.opencontainers.image.source: "https://ghfast.top/github.com/mincka/ha-addons"
  org.opencontainers.image.licenses: "MIT"
